export const projects = [
  {
    title: 'PVC Power',
    description:"Pvcpower is a simple app that can help voters get directions to their closest polling units. I designed the prototype of this app with bubble. I built the app using next.js and typescript.",
    image: '/images/pvcpower.png',
    tags: ['Typescript', 'Reactjs', 'Next.js', 'Chakra UI'],
    // code: 'https://google.com',
    visit: 'https://pvcpower.com ',
    id: 0,
  },
  {
    title: 'Whatellz',
    description:"Whatellz is a whatsapp automation tool built to scale whatsapp marketing for small businesses. Building this app was super challenging and expanded my horizon of knowledge as a developer",
    image: '/images/whatellz.png',
    tags: ['Vue', 'Electron.js', 'Pupeteer', 'Node.js'],
    demo: 'https://www.youtube.com/watch?v=1U-4emwVIZU&feature=youtu.be',
    // visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'We Eat',
    description:"This is a beautiful food delivery app that is similar to ubereat in functionality. It has some really tricky and complex UI, so I definitely learnt a lot of advanced react native techniques while building this app. It was fun and challenging at the same time. ",
    image: '/images/weeat.png',
    tags: ['React Native', 'Typescript', 'Google Maps', 'Node.js'],
    id: 8,
  },
  {
    title: 'Invoicy',
    description: "Tired of editing and documenting my invoices manually, I decided to build this invoice app to automate the process. I'm still working on the app but I already to love the way it's turning out",
    image: '/images/invoicy.png',
    tags: ['Vue 3', 'Tailwind CSS', 'Firebase'],
    // source: 'https://google.com',
    visit: 'https://invoicy-omega.vercel.app/',
    id: 3,
  },
  // {
  //   title: 'Deeviral',
  //   description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
  //   image: '/images/hydaar.png',
  //   tags: ['Vue', 'JavaScript', 'Vuetify'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 4,
  // },
  {
    title: 'Mumble',
    description: "Mumble is an interactive video conference app. It uses WebRTC and websockets for signaling. I built this app after taking a course on WebRTC. It was a fun project that helped to cement my knowledge of WebRTC.",
      image: '/images/mumble.png',
      tags: ['Typescript', 'React', 'Web RTC', 'Node.js'],
    // demo: 'https://www.youtube.com/watch?v=7gBrbEwcM58&t=53s',
    // visit: 'https://csb-cfmxj.vercel.app',
    id: 5,
  },
  {
    title: 'Tubely',
    description: "Tubely was born out of an idea to increase youtube views using watch time metrics. I was proud to complete this project. It was my first successful desktop software with over 1000 downloads and counting.",
      image: '/images/tubely.png',
      tags: ['Vue', 'Electron', 'Node', 'Firebase', 'Puppeteer'],
    demo: 'https://www.youtube.com/watch?v=7gBrbEwcM58&t=53s',
    visit: 'https://csb-cfmxj.vercel.app',
    id: 5,
  },
  {
    title: 'Coinverse',
    description: "Coinverse is one stop spot for in depth data on all crypto currencies, crypto markets, crypto exchanges and crypto news. This was a fun project I built while learning react.",
      image: '/images/coinverse.png',
      tags: ['React', 'Rapid api', 'Ant Design'],
    // source: 'https://google.com',
    visit: 'https://coinverse-lovat.vercel.app/',
    id: 2,
  },
  {
    title: 'Bidhaar',
    description:"I had an idea for an imaginary store and started working on the design. It's no where near being completed but I felt it was pretty enough to include it in my portfolio projects",
    image: '/images/hydaar.png',
    tags: ['Vue', 'JavaScript', 'Vuetify'],
    // source: 'https://google.com',
    visit: 'https://hydaar.vercel.app/',
    id: 6,
  },
  {
    title: 'Telephy',
    description:"Sometime ago, I decided to teach a course on telegram. I then built a telegram bot to handle referral marketing. I got about 150 students in a day and was amazed. Telephy was born to help others build telegram bots without code. So that they also can replicate what I did.",
    image: '/images/telephy.png',
    tags: ['Vue', 'Mongodb', 'Nodejs', 'Nestjs'],
    id: 7,
  },
  {
    title: 'Mega',
    description:"Mega is a ride sharing application that is very similar to uber in looks and functionality. It is for a closed group in the Edo state government, Nigeria. I started building this app using react native at first, but then decided to use flutter. ",
    image: '/images/mega.png',
    tags: ['Flutter', 'Firebase', 'Google Maps'],
    id: 8,
  },
  
];

export const TimeLineData = [
  { year: 2011, text: 'Started learning to code. Learnt enough just to get by'},
  { year: 2013, text: 'Determined to make a career out of it and got really serious about coding', },
  { year: 2015, text: 'Worked as a freelance website developer', },
  { year: 2019, text: 'Started building large projects'},
  { year: 2021, text: 'Started earning from apps that I built' },
];